DROP USER bookstore-api CASCADE;
CREATE USER bookstore-api IDENTIFIED BY password;
GRANT UNLIMITED TABLESPACE TO bookstore-api;
GRANT SELECT ANY DICTIONARY TO bookstore-api;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO bookstore-api;
EXIT;
